name: Docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Run a Docker container
        run: docker run --rm -t hello-world
  windows-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Run a Docker container
        run: docker run --rm -t --platform linux hello-world
  macos-latest:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Run a Docker container
        run: docker run --rm -t hello-world
